[package]
name = "robo-halloween"
version = "0.1.0"
authors = ["poteresting <poteresting@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
rodio = "0.17.1"
rand = "0.8.5"